[General]
network = AdvancedRingNetwork
sim-time-limit = 1s

# Visualización
*.visualizer.*.enabled = true
*.visualizer.*.displayRoutes = false
*.visualizer.*.displayPacketDrops = true
*.visualizer.*.displayLabels = true
*.visualizer.*.animationSpeed = 20

# Tráfico fuente
*.source*.packetInterval = 30us
*.source*.packetSize = 300

# STM niveles y tributarios
**.stmLevel = 1
**.numTributaries = 2

[STM-16]

**.stmLevel = 16
*.source.packetInterval = 125 us
*.source.packetSize = 37440
*.adm*.numTributaries = 1